version: '3.8'

services:
  simple-messenger:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - messenger-network
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  messenger-db:
    container_name: messenger-db
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=messenger_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - messenger-network
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

networks:
  messenger-network:
    driver: bridge