apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
  labels:
    io.kompose.service: app
  name: app
  namespace: messenger
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 80
  selector:
    io.kompose.service: app