apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
  labels:
    io.kompose.service: app
  name: app
  namespace: messenger
spec:
  replicas: 1
  selector:
   matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: BACKEND_URL
              value: http://10.102.70.93:8080/
            - name: NODE_ENV
              value: production
          image: 192.168.49.2:5000/frontend:1.0
          name: frontend
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 9113
              protocol: TCP
      restartPolicy: Always