apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: messenger-db
  name: messenger-db
  namespace: messenger
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: messenger-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: messenger-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: messenger_db
               name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: messenger-db
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always