FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

ENV PATH /app/node_modules/.bin:$PATH

RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent
RUN npm install axios http-proxy-middleware bootstrap react-bootstrap

COPY . ./

EXPOSE 80
EXPOSE 3000

CMD ["npm", "start"]