stages:
  - build
  - test
  - sonar-check
  - quality-check

variables:
  PROJECT_ROOT: "${CI_PROJECT_DIR}"
  FRONTEND_DIR: "${PROJECT_ROOT}/messenger-frontend"
  BACKEND_DIR: "${PROJECT_ROOT}"
  REPORTS_DIR: "${PROJECT_ROOT}/ci-reports"
  
  # Maven settings
  MAVEN_OPTS: "-Dmaven.repo.local=${PROJECT_ROOT}/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  
  # Node settings
  NODE_VERSION: "18"
  NPM_CI_OPTS: "--no-audit --prefer-offline"
  
  # SonarQube
  SONAR_PROJECT_KEY: "DeepPK_messenger_f896f465-8052-4d8a-bb95-1979ae24fdb5"
  SONAR_USER_HOME: "${PROJECT_ROOT}/.sonar"
  GIT_DEPTH: "0"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository
    - messenger-frontend/node_modules/

# ------------------------- BACKEND -------------------------
#backend-build:
#  image: maven:3.8.6-openjdk-18
#  stage: build
#  tags:
#    - messenger
#  script:
#    - cd "${BACKEND_DIR}"
#    - mvn ${MAVEN_CLI_OPTS} clean package -DskipTests
#  artifacts:
#    paths:
#      - target/*.jar
#    expire_in: 1 day

backend-test:
  image: maven:3.8.6-openjdk-18
  stage: test
  tags:
    - messenger
  script:
    - cd "${BACKEND_DIR}"
    - mvn ${MAVEN_CLI_OPTS} test
    - mvn test jacoco:report
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml
    reports:
      junit: target/surefire-reports/*.xml

# ------------------------- FRONTEND -------------------------
#frontend-build:
#  image: node:${NODE_VERSION}-alpine
#  stage: build
#  tags:
#    - messenger
#  script:
#    - cd "${FRONTEND_DIR}"
#    - npm ci ${NPM_CI_OPTS}
#    - npm run build
#  artifacts:
#    paths:
#      - messenger-frontend/build/
#    expire_in: 1 day

frontend-test:
  image: node:${NODE_VERSION}-alpine
  stage: test
  tags:
    - messenger
  variables:
    CI: "true"
  script:
    - cd "${FRONTEND_DIR}"
    - npm ci ${NPM_CI_OPTS}
    - mkdir -p test-report
    - npm test
    - ls -la test-report/
    - ls -la "${FRONTEND_DIR}/test-report/"
    - cp "${FRONTEND_DIR}/test-report/junit-test-results.xml" "${REPORTS_DIR}/frontend-junit.xml" || echo "Report copy failed"
  artifacts:
    reports:
      junit:
        - "${FRONTEND_DIR}/test-report/junit-test-results.xml"
        - "${REPORTS_DIR}/frontend-junit.xml"
    paths:
      - "${FRONTEND_DIR}/coverage/"
      - "${REPORTS_DIR}/"

# ------------------------- SONARQUBE ANALYSIS -------------------------
sonar-check:
  stage: sonar-check
  tags:
    - messenger
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_SCANNER_OPTS: "-Xmx512m"
  script:
    - echo "Running SonarQube analysis for both projects"
    # Анализ бэкенда
    - sonar-scanner
      -Dsonar.projectKey=$SONAR_PROJECT_KEY
      -Dsonar.projectName=Messenger
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.sources=src/main/java
      -Dsonar.java.binaries=target/classes
      -Dsonar.tests=src/test/java
      -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      -Dsonar.language=java
    # Анализ фронтенда
    - cd frontend
    - sonar-scanner
      -Dsonar.projectKey=$SONAR_PROJECT_KEY
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.sources=src
      -Dsonar.tests=src
      -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      -Dsonar.testExecutionReportPaths=junit-test-results.xml
      -Dsonar.language=js
  dependencies:
    - backend-test
    - frontend-test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'

