stages:
  - build
  - test
  - sonar-check

variables:
  PROJECT_ROOT: "${CI_PROJECT_DIR}"
  FRONTEND_DIR: "${PROJECT_ROOT}/messenger-frontend"
  BACKEND_DIR: "${PROJECT_ROOT}"
  
  # Maven settings
  MAVEN_OPTS: "-Dmaven.repo.local=${PROJECT_ROOT}/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  
  # Node settings
  NODE_VERSION: "18"
  
  # SonarQube
  SONAR_PROJECT_KEY: "DeepPK_messenger_f896f465-8052-4d8a-bb95-1979ae24fdb5"
  SONAR_USER_HOME: "${PROJECT_ROOT}/.sonar"
  SONAR_HOST_URL: "http://192.168.59.129:9000"
  GIT_DEPTH: "0"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository
    - target/classes/
    - messenger-frontend/node_modules/
    - ci-reports/

# ------------------------- BACKEND -------------------------
backend-build:
  image: maven:3.8.6-openjdk-18
  stage: build
  tags:
    - messenger
  script:
    - cd "${BACKEND_DIR}"
    - mvn ${MAVEN_CLI_OPTS} clean package -DskipTests
  artifacts:
    paths:
      - target/classes/
      - target/*.jar
    expire_in: 1 day

backend-test:
  image: maven:3.8.6-openjdk-18
  stage: test
  tags:
    - messenger
  script:
    - cd "${BACKEND_DIR}"
    - mvn ${MAVEN_CLI_OPTS} test jacoco:report-aggregate
  artifacts:
    paths:
      - target/site/jacoco-aggregate/jacoco.xml
    reports:
      junit: target/surefire-reports/TEST-*.xml

# ------------------------- FRONTEND ------------------------
frontend-build:
  image: node:${NODE_VERSION}-alpine
  stage: build
  tags:
    - messenger
  script:
    - cd "${FRONTEND_DIR}"
    - npm ci ${NPM_CI_OPTS}
    - npm run build
  artifacts:
    paths:
      - messenger-frontend/build/
    expire_in: 1 day

frontend-test:
  image: node:${NODE_VERSION}-alpine
  stage: test
  tags:
    - messenger
  script:
    - cd "${FRONTEND_DIR}"
    - npm ci
    - npm test -- --watchAll=false

# ------------------------- SONARQUBE ANALYSIS -------------------------
sonar-check:
  stage: sonar-check
  tags:
    - messenger
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_SCANNER_OPTS: "-Xmx512m"
  script:
    - sonar-scanner
      -Dsonar.projectKey=$SONAR_PROJECT_KEY
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.sources=src/main/java,messenger-frontend/src
      -Dsonar.java.binaries=target/classes/
      -Dsonar.qualitygate.wait=true
      -Dsonar.qualitygate.timeout=600
      -Dsonar.analysis.force=true
