stages:
  - build
  - test
  - sonar-check
  - quality-check

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  SONAR_PROJECT_KEY: "DeepPK_messenger"

cache:
  key: maven
  paths:
    - .m2/repository

build:
  image: maven:3.8.6-openjdk-18
  stage: build
  tags:
    - messenger
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

test:
  image: maven:3.8.6-openjdk-18
  stage: test
  tags:
    - messenger
  script:
    - mvn test jacoco:report
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml
    reports:
      junit: target/surefire-reports/*.xml

sonar-check:
  image: maven:3-openjdk-17
  stage: sonar-check
  tags:
    - messenger
  script:
    - mvn clean install
    - mvn sonar:sonar 
      -Dsonar.projectKey=$SONAR_PROJECT_KEY
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      -Dsonar.qualitygate.wait=true
  dependencies:
    - test

check-metrics:
  image: curlimages/curl:latest
  stage: quality-check
  tags:
    - messenger
  script:
    - |
      while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
        STATUS=$(curl -s -u $SONAR_TOKEN: "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=$PROJECT_KEY" | jq -r '.projectStatus.status')
        
        if [ "$STATUS" = "OK" ]; then
          echo "Quality Gate passed"
          break
        elif [ "$STATUS" = "ERROR" ]; then
          echo "Quality Gate failed"
          exit 1
        fi

        sleep 30
        ATTEMPT=$((ATTEMPT+1))
      done

      # Проверка покрытия кода
      COVERAGE=$(curl -s -u $SONAR_TOKEN: "$SONAR_HOST_URL/api/measures/component?component=$PROJECT_KEY&metricKeys=coverage" | jq -r '.component.measures[0].value')
      if [ $(echo "$COVERAGE < 80" | bc) -eq 1 ]; then
        echo "Code coverage $COVERAGE% < 80%"
        exit 1
      fi

      # Проверка критических ошибок
      CRITICAL_ISSUES=$(curl -s -u $SONAR_TOKEN: "$SONAR_HOST_URL/api/issues/search?componentKeys=$PROJECT_KEY&severities=CRITICAL" | jq -r '.total')
      if [ "$CRITICAL_ISSUES" -gt 0 ]; then
        echo "Found $CRITICAL_ISSUES critical issues"
        exit 1
      fi

